"""MapProtocol - the abstract contract a map implementation must satisfy.

Uses PEP 544 Protocol so any conforming object works without inheritance.
"""
from __future__ import annotations

from typing import List, Optional, Protocol, Set, Union, runtime_checkable

from dipworkpy.geo_model import Edge, FieldType, Passable


@runtime_checkable
class MapProtocol(Protocol):
    """Abstract map. Implementations: StandardMap, InlineMap."""
    map_id: str

    # Fields
    def field_exists(self, fld: str) -> bool: ...
    def field_type(self, fld: str) -> FieldType: ...
    def superfield_of(self, fld: str) -> str: ...
    def subfields_of(self, fld: str) -> List[str]: ...
    def is_supply_center(self, fld: str) -> bool: ...
    def home_center_of(self, fld: str) -> Optional[str]: ...

    # Edges
    def edge(self, frm: str, to: str) -> Optional[Edge]: ...
    def neighbors(self, fld: str) -> Set[str]: ...

    # Convenience derived from edge()
    def army_passable(self, frm: str, to: str) -> bool: ...
    def fleet_passable(self, frm: str, to: str) -> Union[Passable, str]: ...
    def convoy_passable(self, frm: str, to: str) -> bool: ...
